"""phase0 venues courts court_id

Revision ID: 39c7650a6232
Revises: ffdacb7fb201
Create Date: 2026-06-29 13:24:23.374639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c7650a6232'
down_revision: Union[str, Sequence[str], None] = 'ffdacb7fb201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('venue_id', sa.String(), nullable=False),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courts_sport'), ['sport'], unique=False)
        batch_op.create_index(batch_op.f('ix_courts_venue_id'), ['venue_id'], unique=False)

    # court_id column + index (FK omitted: SQLite doesn't enforce FKs without
    # PRAGMA foreign_keys=ON, and an unnamed FK breaks batch recreate).
    op.add_column('bookings', sa.Column('court_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_bookings_court_id'), 'bookings', ['court_id'], unique=False)

    # Backfill existing bookings to their sport's court (deterministic id: court-{sport}).
    op.execute('UPDATE bookings SET court_id = \'court-\' || "sportSlug" WHERE court_id IS NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_court_id'), table_name='bookings')
    op.drop_column('bookings', 'court_id')

    with op.batch_alter_table('courts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courts_venue_id'))
        batch_op.drop_index(batch_op.f('ix_courts_sport'))

    op.drop_table('courts')
    op.drop_table('venues')
    # ### end Alembic commands ###
