"""phase1 schedule rules exceptions

Revision ID: cbcc5e7f4b05
Revises: 39c7650a6232
Create Date: 2026-06-29 13:40:57.237301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbcc5e7f4b05'
down_revision: Union[str, Sequence[str], None] = '39c7650a6232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_exceptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('court_id', sa.String(), nullable=False),
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('open_time', sa.String(), nullable=True),
    sa.Column('close_time', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_exceptions_court_id'), ['court_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_exceptions_day'), ['day'], unique=False)

    op.create_table('schedule_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('court_id', sa.String(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.String(), nullable=False),
    sa.Column('close_time', sa.String(), nullable=False),
    sa.Column('slot_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_rules_court_id'), ['court_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_rules_court_id'))

    op.drop_table('schedule_rules')
    with op.batch_alter_table('schedule_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_exceptions_day'))
        batch_op.drop_index(batch_op.f('ix_schedule_exceptions_court_id'))

    op.drop_table('schedule_exceptions')
    # ### end Alembic commands ###
